# CrowdSec Targets
# Included conditionally in main Makefile

##@ CrowdSec Security

##@help crowdsec-metrics
## Shows the internal metrics of the CrowdSec LAPI, including parsed logs, triggered scenarios, and active bouncers.
.PHONY: crowdsec-metrics
crowdsec-metrics: ## Show CrowdSec metrics (parsed logs, overflows)
	@$(call check_service,crowdsec,cscli metrics)

##@help crowdsec-decisions
## Lists all active decisions (bans) currently enforced by the CrowdSec firewall.
.PHONY: crowdsec-decisions
crowdsec-decisions: ## List active CrowdSec decisions (bans)
	@$(call check_service,crowdsec,cscli decisions list)

##@help crowdsec-alerts
## Lists the most recent security alerts generated by CrowdSec scenarios.
.PHONY: crowdsec-alerts
crowdsec-alerts: ## List recent CrowdSec alerts
	@$(call check_service,crowdsec,cscli alerts list)

##@help crowdsec-unban
## Manually removes a ban for a specific IP address.
## - Usage: make crowdsec-unban 1.2.3.4
.PHONY: crowdsec-unban
crowdsec-unban: ## Unban an IP address (usage: make crowdsec-unban 1.2.3.4)
	@if [ -z "$(SERVICE_ARGS)" ]; then \
		echo "Error: Please specify at least one IP address (e.g., 'make crowdsec-unban 1.2.3.4')."; \
		exit 1; \
	fi; \
	for ip in $(SERVICE_ARGS); do \
		echo "Removing ban for IP: $$ip from CrowdSec LAPI..."; \
		$(call check_service,crowdsec,cscli decisions delete --ip $$ip); \
		echo "Removing ban for IP: $$ip from Redis Cache..."; \
		$(call check_service,redis,valkey-cli -a "$${REDIS_PASSWORD}" --no-auth-warning -n 0 DEL "$$ip" "$${ip}_captcha") >/dev/null 2>&1 || true; \
	done

##@help crowdsec-ban
## Manually bans a specific IP address for 4 hours.
## - Usage: make crowdsec-ban 1.2.3.4
.PHONY: crowdsec-ban
crowdsec-ban: ## Ban an IP address manually (usage: make crowdsec-ban 1.2.3.4)
	@if [ -z "$(SERVICE_ARGS)" ]; then \
		echo "Error: Please specify at least one IP address (e.g., 'make crowdsec-ban 1.2.3.4')."; \
		exit 1; \
	fi; \
	for ip in $(SERVICE_ARGS); do \
		echo "Adding ban for IP: $$ip..."; \
		$(call check_service,crowdsec,cscli decisions add --ip $$ip --reason 'manual ban'); \
	done


##@help crowdsec-appsec
## Shows the status of the CrowdSec AppSec WAF, including loaded rules, virtual patches, and payload inspection metrics.
.PHONY: crowdsec-appsec
crowdsec-appsec: ## Show AppSec WAF status: loaded configs, rules, and metrics
	@echo "=== AppSec Configs ==="
	@$(call check_service,crowdsec,cscli appsec-configs list)
	@echo ""
	@echo "=== AppSec Rules (summary) ==="
	@$(call check_service,crowdsec,cscli appsec-rules list)
	@echo ""
	@echo "=== AppSec Metrics ==="
	@$(call check_service,crowdsec,cscli metrics show appsec)

##@help crowdsec-ban-country
## Bans all IP addresses from one or more countries.
## - Downloads the CIDR ranges from ipdeny.com and adds them to CrowdSec.
## - Usage: make crowdsec-ban-country CN RU
.PHONY: crowdsec-ban-country
crowdsec-ban-country: ## Ban all IPs from one or more countries (usage: make crowdsec-ban-country CN RU KP)
	@if [ -z "$(SERVICE_ARGS)" ]; then \
		echo "Error: Please specify at least one country code (e.g., 'make crowdsec-ban-country CN RU')."; \
		exit 1; \
	fi; \
	./scripts/crowdsec-geoblock.sh ban $(SERVICE_ARGS)

##@help crowdsec-unban-country
## Removes all bans associated with one or more specific country codes.
## - Usage: make crowdsec-unban-country CN RU
.PHONY: crowdsec-unban-country
crowdsec-unban-country: ## Remove all bans for one or more countries (usage: make crowdsec-unban-country CN RU)
	@if [ -z "$(SERVICE_ARGS)" ]; then \
		echo "Error: Please specify at least one country code (e.g., 'make crowdsec-unban-country CN')."; \
		exit 1; \
	fi; \
	./scripts/crowdsec-geoblock.sh unban $(SERVICE_ARGS)

##@help crowdsec-db-shell
## Opens an interactive psql terminal inside the CrowdSec PostgreSQL container.
.PHONY: crowdsec-db-shell
crowdsec-db-shell: ## Open interactive psql terminal in CrowdSec Postgres DB
	@$(call check_service,crowdsec-db,psql -U $${CROWDSEC_DB_USER:-crowdsec} -d $${CROWDSEC_DB_NAME:-crowdsec})

##@help crowdsec-db-stats
## Displays table sizes, active connections, and record counts for the CrowdSec Postgres DB.
.PHONY: crowdsec-db-stats
crowdsec-db-stats: ## Show CrowdSec Postgres DB stats (size, connection count, row counts)
	@echo "=== CrowdSec PostgreSQL Database Stats ==="
	@$(call check_service,crowdsec-db,psql -U $${CROWDSEC_DB_USER:-crowdsec} -d $${CROWDSEC_DB_NAME:-crowdsec} -c "\
		SELECT pg_size_pretty(pg_database_size('$${CROWDSEC_DB_NAME:-crowdsec}')) AS database_size; \
		SELECT count(*) AS active_connections FROM pg_stat_activity WHERE datname = '$${CROWDSEC_DB_NAME:-crowdsec}'; \
		SELECT relname AS table_name, n_live_tup AS estimated_rows FROM pg_stat_user_tables ORDER BY n_live_tup DESC;")

##@help crowdsec-db-vacuum
## Runs VACUUM ANALYZE on the CrowdSec Postgres DB to optimize indexes and reclaim disk space.
.PHONY: crowdsec-db-vacuum
crowdsec-db-vacuum: ## Optimize CrowdSec Postgres DB indexes and reclaim space (VACUUM ANALYZE)
	@echo "Running VACUUM ANALYZE on CrowdSec database..."
	@$(call check_service,crowdsec-db,psql -U $${CROWDSEC_DB_USER:-crowdsec} -d $${CROWDSEC_DB_NAME:-crowdsec} -c "VACUUM ANALYZE;")
	@echo "✅ Database optimization complete."

##@help crowdsec-db-dump
## Dumps a compressed SQL backup of the CrowdSec PostgreSQL database into backups/.
.PHONY: crowdsec-db-dump
crowdsec-db-dump: ## Create compressed SQL backup of CrowdSec DB in backups/
	@mkdir -p backups
	@DUMP_FILE="backups/crowdsec-db-$$(date +%Y%m%d_%H%M%S).sql.gz"; \
	echo "Dumping CrowdSec database to $$DUMP_FILE..."; \
	$(call check_service,crowdsec-db,pg_dump -U $${CROWDSEC_DB_USER:-crowdsec} $${CROWDSEC_DB_NAME:-crowdsec}) | gzip > "$$DUMP_FILE"; \
	echo "✅ Backup created successfully: $$DUMP_FILE"

