#!/bin/bash

# =============================================================================
# PHASE 2b: Generate acquis.yaml (CrowdSec log acquisition config)
# =============================================================================
# acquis.yaml is generated from acquis-base.yaml. When AppSec is enabled,
# the AppSec listener block is appended and its required collections are
# injected into COLLECTIONS so CrowdSec downloads them at startup.

ACQUIS_BASE="./config/crowdsec/acquis-base.yaml"
ACQUIS_OUT="./config/crowdsec/acquis.yaml"

if [ ! -f "$ACQUIS_BASE" ]; then
    echo "   ❌ Error: $ACQUIS_BASE not found!"
    exit 1
fi

TMP_ACQUIS=$(mktemp)
cp "$ACQUIS_BASE" "$TMP_ACQUIS"

if [[ "$CROWDSEC_ENABLE" == "true" ]] && [[ "$CROWDSEC_APPSEC_ENABLE" == "true" ]]; then
    # Append AppSec listener block
    cat >> "$TMP_ACQUIS" << 'EOF'

---

# --- AppSec (WAF) Configuration --- (auto-generated by start.sh)
appsec_configs:
  - crowdsecurity/appsec-default
labels:
  type: appsec
listen_addr: 0.0.0.0:7422
source: appsec
name: traefikAppSec
EOF

    # Inject AppSec collections into COLLECTIONS if not already present
    APPSEC_COLLECTIONS="crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
    for col in $APPSEC_COLLECTIONS; do
        if [[ "$CROWDSEC_COLLECTIONS" != *"$col"* ]]; then
            CROWDSEC_COLLECTIONS="$CROWDSEC_COLLECTIONS $col"
        fi
    done
    export CROWDSEC_COLLECTIONS
fi

# Idempotent write: only update acquis.yaml if content changed
if [ -f "$ACQUIS_OUT" ] && cmp -s "$TMP_ACQUIS" "$ACQUIS_OUT"; then
    rm "$TMP_ACQUIS"
else
    cat "$TMP_ACQUIS" > "$ACQUIS_OUT"
    rm "$TMP_ACQUIS"
fi

# =============================================================================
# PHASE 2c: Generate profiles.yaml (CrowdSec remediation profiles)
# =============================================================================
# Conditionally inject CAPTCHA remediation only if fully configured.

PROFILES_BASE="./config/crowdsec/profiles-base.yaml"
PROFILES_OUT="./config/crowdsec/profiles.yaml"

if [ ! -f "$PROFILES_BASE" ]; then
    echo "   ❌ Error: $PROFILES_BASE not found!"
    exit 1
fi

TMP_PROFILES=$(mktemp)
cp "$PROFILES_BASE" "$TMP_PROFILES"

# Check if CAPTCHA registry has active configurations
HAS_ACTIVE_CAPTCHAS=false
CAPTCHA_KEYS_CSV="./config/crowdsec/captcha_keys.csv"
CAPTCHA_KEYS_DIST="./config/crowdsec/captcha_keys.csv.dist"

if [ ! -f "$CAPTCHA_KEYS_CSV" ]; then
    if [ -f "$CAPTCHA_KEYS_DIST" ]; then
        echo "   📄 Initializing captcha_keys.csv from template..."
        cp "$CAPTCHA_KEYS_DIST" "$CAPTCHA_KEYS_CSV"
    fi
fi

if [ -f "$CAPTCHA_KEYS_CSV" ]; then
    # Filter out comment lines and empty lines, check if there is at least one row containing a comma
    if grep -v -E '^(#|$|[[:space:]]*$)' "$CAPTCHA_KEYS_CSV" | grep -q ','; then
        HAS_ACTIVE_CAPTCHAS=true
    fi
fi

if [ "$HAS_ACTIVE_CAPTCHAS" = "true" ]; then
    cat >> "$TMP_PROFILES" << 'EOF'

---

# -----------------------------------------------------------------------------
# Profile 2: CAPTCHA Remediation for HTTP Scenarios (4 hours)
# -----------------------------------------------------------------------------
# HTTP-based attacks (crawlers, bad bots) get a CAPTCHA instead of a ban.
# Excludes AppSec (WAF) since those are high-confidence malicious.

name: captcha_remediation
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && (Alert.GetScenario() contains "http" || Alert.GetScenario() contains "traefik-flood-429") && !(Alert.GetScenario() contains "appsec")
decisions:
 - type: captcha
   duration: 4h
on_success: break
EOF
fi

# Append the fallback/default aggressive bans
cat >> "$TMP_PROFILES" << 'EOF'

---

# -----------------------------------------------------------------------------
# Profile 3: Standard Aggressive Ban (24 hours)
# -----------------------------------------------------------------------------
# Default ban duration increased from 4h to 24h for all IP-based remediation.

name: aggressive_ban
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip"
decisions:
 - type: ban
   duration: 24h   # 24 hours (default is 4h)
on_success: break

---

# -----------------------------------------------------------------------------
# Profile 4: Range-based Attacks (48 hours)
# -----------------------------------------------------------------------------
# If the attack targets a range (subnet), apply a 48-hour ban to the range.

name: range_ban
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Range"
decisions:
 - type: ban
   duration: 48h
on_success: break
EOF

# Idempotent write: only update profiles.yaml if content changed
if [ -f "$PROFILES_OUT" ] && cmp -s "$TMP_PROFILES" "$PROFILES_OUT"; then
    rm "$TMP_PROFILES"
else
    cat "$TMP_PROFILES" > "$PROFILES_OUT"
    rm "$TMP_PROFILES"
fi

# =============================================================================
# PHASE 2d: Handle custom scenarios
# =============================================================================
SCENARIO_SRC="./config/crowdsec/scenarios/traefik-flood-429.yaml.dist"
SCENARIO_DST="./config/crowdsec/scenarios/traefik-flood-429.yaml"

if [[ "${CROWDSEC_RATE_LIMIT_BAN_ENABLE:-true}" == "true" ]]; then
    if [ -f "$SCENARIO_SRC" ]; then
        # Copy dynamically to ensure update-on-boot works
        cp "$SCENARIO_SRC" "$SCENARIO_DST"
    fi
else
    if [ -f "$SCENARIO_DST" ]; then
        rm -f "$SCENARIO_DST"
    fi
fi

# Build Compose command with or without CrowdSec profile
# Enforce project name to avoid conflicts when running from within a container
COMPOSE_BASE="docker compose"
if [ -n "$PROJECT_NAME" ]; then
    COMPOSE_BASE="docker compose -p $PROJECT_NAME"
fi

COMPOSE_CMD="$COMPOSE_BASE"
if [[ "$CROWDSEC_ENABLE" == "true" ]]; then
    COMPOSE_CMD="$COMPOSE_CMD --profile crowdsec"
fi

# Print consolidated security shields status
if [[ "$CROWDSEC_ENABLE" == "true" ]]; then
    SHIELDS="Firewall"
    if [[ "$CROWDSEC_APPSEC_ENABLE" == "true" ]]; then
        SHIELDS="$SHIELDS, WAF (AppSec)"
    fi
    if [ "$HAS_ACTIVE_CAPTCHAS" = "true" ]; then
        SHIELDS="$SHIELDS, CAPTCHA"
    fi
    if [[ "${CROWDSEC_RATE_LIMIT_BAN_ENABLE:-true}" == "true" ]]; then
        SHIELDS="$SHIELDS, Rate-Limit"
    fi
    echo "   🛡️ Security Shields: ${SHIELDS} enabled."
else
    echo "   ⚠️ CrowdSec firewall is DISABLED."
fi
